# Type stub file for paho.mqtt.client
# This suppresses IDE warnings for Raspberry Pi-only libraries

from typing import Any, Callable, Optional

class Client:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def connect(self, host: str, port: int = 1883, keepalive: int = 60) -> int: ...
    def disconnect(self) -> int: ...
    def subscribe(self, topic: str, qos: int = 0) -> tuple: ...
    def publish(self, topic: str, payload: Any = None, qos: int = 0, retain: bool = False) -> Any: ...
    def loop_forever(self) -> None: ...
    def on_connect: Optional[Callable] = None
    def on_message: Optional[Callable] = None
    def on_disconnect: Optional[Callable] = None
